version: '3.7'
services:
  postgres:
    image: postgres:17-alpine
    container_name: pg-db-bosta
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg-db:/var/lib/postgresql/data
volumes:
  pg-db:
